/* Generated by Yosys 0.35+29 (git sha1 2a18fe5fa, clang++  -fPIC -Os) */

(* top =  1  *)
(* src = "./full_adder.v:1.1-40.10" *)
module full_adder(i_bit1, i_bit2, i_cin, o_sum, o_carry);
  (* src = "./mycells.v:12.7-12.8" *)
  wire _00_;
  (* src = "./mycells.v:12.10-12.11" *)
  wire _01_;
  (* src = "./mycells.v:13.8-13.9" *)
  wire _02_;
  (* src = "./mycells.v:2.7-2.8" *)
  wire _03_;
  (* src = "./mycells.v:3.8-3.9" *)
  wire _04_;
  (* src = "./full_adder.v:17.11-17.22" *)
  wire _05_;
  (* src = "./full_adder.v:18.11-18.22" *)
  wire _06_;
  wire _07_;
  (* src = "./full_adder.v:14.11-14.18" *)
  wire _08_;
  (* src = "./mycells.v:13.12-13.20" *)
  wire _09_;
  (* src = "./mycells.v:13.14-13.19" *)
  wire _10_;
  (* src = "./mycells.v:3.12-3.14" *)
  wire _11_;
  (* src = "./full_adder.v:22.15-27.7|./mycells.v:3.12-3.14" *)
  wire _12_;
  (* src = "./full_adder.v:22.15-27.7|./mycells.v:2.7-2.8" *)
  wire _13_;
  (* src = "./full_adder.v:22.15-27.7|./mycells.v:3.8-3.9" *)
  wire _14_;
  (* src = "./full_adder.v:22.15-27.7|./mycells.v:3.12-3.14" *)
  wire _15_;
  (* src = "./full_adder.v:22.15-27.7|./mycells.v:2.7-2.8" *)
  wire _16_;
  (* src = "./full_adder.v:22.15-27.7|./mycells.v:3.8-3.9" *)
  wire _17_;
  (* src = "./full_adder.v:22.15-27.7|./mycells.v:13.12-13.20" *)
  wire _18_;
  (* src = "./full_adder.v:22.15-27.7|./mycells.v:13.14-13.19" *)
  wire _19_;
  (* src = "./full_adder.v:22.15-27.7|./mycells.v:12.7-12.8" *)
  wire _20_;
  (* src = "./full_adder.v:22.15-27.7|./mycells.v:12.10-12.11" *)
  wire _21_;
  (* src = "./full_adder.v:22.15-27.7|./mycells.v:13.8-13.9" *)
  wire _22_;
  (* src = "./full_adder.v:22.15-27.7|./mycells.v:13.12-13.20" *)
  wire _23_;
  (* src = "./full_adder.v:22.15-27.7|./mycells.v:13.14-13.19" *)
  wire _24_;
  (* src = "./full_adder.v:22.15-27.7|./mycells.v:12.7-12.8" *)
  wire _25_;
  (* src = "./full_adder.v:22.15-27.7|./mycells.v:12.10-12.11" *)
  wire _26_;
  (* src = "./full_adder.v:22.15-27.7|./mycells.v:13.8-13.9" *)
  wire _27_;
  (* src = "./full_adder.v:22.15-27.7|./mycells.v:13.12-13.20" *)
  wire _28_;
  (* src = "./full_adder.v:22.15-27.7|./mycells.v:13.14-13.19" *)
  wire _29_;
  (* src = "./full_adder.v:22.15-27.7|./mycells.v:12.7-12.8" *)
  wire _30_;
  (* src = "./full_adder.v:22.15-27.7|./mycells.v:12.10-12.11" *)
  wire _31_;
  (* src = "./full_adder.v:22.15-27.7|./mycells.v:13.8-13.9" *)
  wire _32_;
  (* src = "./full_adder.v:22.15-27.7|./half-adder.v:11.10-11.16" *)
  wire _33_;
  (* src = "./full_adder.v:22.15-27.7|./half-adder.v:12.10-12.16" *)
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  (* src = "./full_adder.v:22.15-27.7|./half-adder.v:14.10-14.17" *)
  wire _38_;
  (* src = "./full_adder.v:22.15-27.7|./half-adder.v:13.10-13.15" *)
  wire _39_;
  (* src = "./full_adder.v:28.15-33.7|./mycells.v:3.12-3.14" *)
  wire _40_;
  (* src = "./full_adder.v:28.15-33.7|./mycells.v:2.7-2.8" *)
  wire _41_;
  (* src = "./full_adder.v:28.15-33.7|./mycells.v:3.8-3.9" *)
  wire _42_;
  (* src = "./full_adder.v:28.15-33.7|./mycells.v:3.12-3.14" *)
  wire _43_;
  (* src = "./full_adder.v:28.15-33.7|./mycells.v:2.7-2.8" *)
  wire _44_;
  (* src = "./full_adder.v:28.15-33.7|./mycells.v:3.8-3.9" *)
  wire _45_;
  (* src = "./full_adder.v:28.15-33.7|./mycells.v:13.12-13.20" *)
  wire _46_;
  (* src = "./full_adder.v:28.15-33.7|./mycells.v:13.14-13.19" *)
  wire _47_;
  (* src = "./full_adder.v:28.15-33.7|./mycells.v:12.7-12.8" *)
  wire _48_;
  (* src = "./full_adder.v:28.15-33.7|./mycells.v:12.10-12.11" *)
  wire _49_;
  (* src = "./full_adder.v:28.15-33.7|./mycells.v:13.8-13.9" *)
  wire _50_;
  (* src = "./full_adder.v:28.15-33.7|./mycells.v:13.12-13.20" *)
  wire _51_;
  (* src = "./full_adder.v:28.15-33.7|./mycells.v:13.14-13.19" *)
  wire _52_;
  (* src = "./full_adder.v:28.15-33.7|./mycells.v:12.7-12.8" *)
  wire _53_;
  (* src = "./full_adder.v:28.15-33.7|./mycells.v:12.10-12.11" *)
  wire _54_;
  (* src = "./full_adder.v:28.15-33.7|./mycells.v:13.8-13.9" *)
  wire _55_;
  (* src = "./full_adder.v:28.15-33.7|./mycells.v:13.12-13.20" *)
  wire _56_;
  (* src = "./full_adder.v:28.15-33.7|./mycells.v:13.14-13.19" *)
  wire _57_;
  (* src = "./full_adder.v:28.15-33.7|./mycells.v:12.7-12.8" *)
  wire _58_;
  (* src = "./full_adder.v:28.15-33.7|./mycells.v:12.10-12.11" *)
  wire _59_;
  (* src = "./full_adder.v:28.15-33.7|./mycells.v:13.8-13.9" *)
  wire _60_;
  (* src = "./full_adder.v:28.15-33.7|./half-adder.v:11.10-11.16" *)
  wire _61_;
  (* src = "./full_adder.v:28.15-33.7|./half-adder.v:12.10-12.16" *)
  wire _62_;
  wire _63_;
  wire _64_;
  wire _65_;
  (* src = "./full_adder.v:28.15-33.7|./half-adder.v:14.10-14.17" *)
  wire _66_;
  (* src = "./full_adder.v:28.15-33.7|./half-adder.v:13.10-13.15" *)
  wire _67_;
  (* hdlname = "half_adder1 i_bit1" *)
  (* src = "./full_adder.v:22.15-27.7|./half-adder.v:11.10-11.16" *)
  wire \half_adder1.i_bit1 ;
  (* hdlname = "half_adder1 i_bit2" *)
  (* src = "./full_adder.v:22.15-27.7|./half-adder.v:12.10-12.16" *)
  wire \half_adder1.i_bit2 ;
  (* hdlname = "half_adder1 o_carry" *)
  (* src = "./full_adder.v:22.15-27.7|./half-adder.v:14.10-14.17" *)
  wire \half_adder1.o_carry ;
  (* hdlname = "half_adder1 o_sum" *)
  (* src = "./full_adder.v:22.15-27.7|./half-adder.v:13.10-13.15" *)
  wire \half_adder1.o_sum ;
  (* hdlname = "half_adder2 i_bit1" *)
  (* src = "./full_adder.v:28.15-33.7|./half-adder.v:11.10-11.16" *)
  wire \half_adder2.i_bit1 ;
  (* hdlname = "half_adder2 i_bit2" *)
  (* src = "./full_adder.v:28.15-33.7|./half-adder.v:12.10-12.16" *)
  wire \half_adder2.i_bit2 ;
  (* hdlname = "half_adder2 o_carry" *)
  (* src = "./full_adder.v:28.15-33.7|./half-adder.v:14.10-14.17" *)
  wire \half_adder2.o_carry ;
  (* hdlname = "half_adder2 o_sum" *)
  (* src = "./full_adder.v:28.15-33.7|./half-adder.v:13.10-13.15" *)
  wire \half_adder2.o_sum ;
  (* src = "./full_adder.v:17.11-17.22" *)
  wire half_carry1;
  (* src = "./full_adder.v:18.11-18.22" *)
  wire half_carry2;
  (* src = "./full_adder.v:16.11-16.20" *)
  wire half_sum1;
  (* src = "./full_adder.v:10.11-10.17" *)
  input i_bit1;
  wire i_bit1;
  (* src = "./full_adder.v:11.11-11.17" *)
  input i_bit2;
  wire i_bit2;
  (* src = "./full_adder.v:12.11-12.16" *)
  input i_cin;
  wire i_cin;
  (* src = "./full_adder.v:14.11-14.18" *)
  output o_carry;
  wire o_carry;
  (* src = "./full_adder.v:13.11-13.16" *)
  output o_sum;
  wire o_sum;
  assign _09_ = ~ (* src = "./mycells.v:13.12-13.20" *) _10_;
  assign _10_ = _00_ | (* src = "./mycells.v:13.14-13.19" *) _01_;
  assign _11_ = ~ (* src = "./mycells.v:3.12-3.14" *) _03_;
  assign _12_ = ~ (* src = "./full_adder.v:22.15-27.7|./mycells.v:3.12-3.14" *) _13_;
  assign _15_ = ~ (* src = "./full_adder.v:22.15-27.7|./mycells.v:3.12-3.14" *) _16_;
  assign _18_ = ~ (* src = "./full_adder.v:22.15-27.7|./mycells.v:13.12-13.20" *) _19_;
  assign _19_ = _20_ | (* src = "./full_adder.v:22.15-27.7|./mycells.v:13.14-13.19" *) _21_;
  assign _23_ = ~ (* src = "./full_adder.v:22.15-27.7|./mycells.v:13.12-13.20" *) _24_;
  assign _24_ = _25_ | (* src = "./full_adder.v:22.15-27.7|./mycells.v:13.14-13.19" *) _26_;
  assign _28_ = ~ (* src = "./full_adder.v:22.15-27.7|./mycells.v:13.12-13.20" *) _29_;
  assign _29_ = _30_ | (* src = "./full_adder.v:22.15-27.7|./mycells.v:13.14-13.19" *) _31_;
  assign _40_ = ~ (* src = "./full_adder.v:28.15-33.7|./mycells.v:3.12-3.14" *) _41_;
  assign _43_ = ~ (* src = "./full_adder.v:28.15-33.7|./mycells.v:3.12-3.14" *) _44_;
  assign _46_ = ~ (* src = "./full_adder.v:28.15-33.7|./mycells.v:13.12-13.20" *) _47_;
  assign _47_ = _48_ | (* src = "./full_adder.v:28.15-33.7|./mycells.v:13.14-13.19" *) _49_;
  assign _51_ = ~ (* src = "./full_adder.v:28.15-33.7|./mycells.v:13.12-13.20" *) _52_;
  assign _52_ = _53_ | (* src = "./full_adder.v:28.15-33.7|./mycells.v:13.14-13.19" *) _54_;
  assign _56_ = ~ (* src = "./full_adder.v:28.15-33.7|./mycells.v:13.12-13.20" *) _57_;
  assign _57_ = _58_ | (* src = "./full_adder.v:28.15-33.7|./mycells.v:13.14-13.19" *) _59_;
  assign _05_ = half_carry1;
  assign _06_ = half_carry2;
  assign o_carry = _08_;
  assign _61_ = \half_adder2.i_bit1 ;
  assign _62_ = \half_adder2.i_bit2 ;
  assign \half_adder2.o_carry  = _66_;
  assign \half_adder2.o_sum  = _67_;
  assign _60_ = _56_;
  assign _58_ = _66_;
  assign _59_ = _65_;
  assign _67_ = _60_;
  assign _55_ = _51_;
  assign _53_ = _61_;
  assign _54_ = _62_;
  assign _65_ = _55_;
  assign _50_ = _46_;
  assign _48_ = _63_;
  assign _49_ = _64_;
  assign _66_ = _50_;
  assign _45_ = _43_;
  assign _44_ = _62_;
  assign _64_ = _45_;
  assign _42_ = _40_;
  assign _41_ = _61_;
  assign _63_ = _42_;
  assign \half_adder2.i_bit1  = i_cin;
  assign \half_adder2.i_bit2  = half_sum1;
  assign half_carry2 = \half_adder2.o_carry ;
  assign o_sum = \half_adder2.o_sum ;
  assign _33_ = \half_adder1.i_bit1 ;
  assign _34_ = \half_adder1.i_bit2 ;
  assign \half_adder1.o_carry  = _38_;
  assign \half_adder1.o_sum  = _39_;
  assign _32_ = _28_;
  assign _30_ = _38_;
  assign _31_ = _37_;
  assign _39_ = _32_;
  assign _27_ = _23_;
  assign _25_ = _33_;
  assign _26_ = _34_;
  assign _37_ = _27_;
  assign _22_ = _18_;
  assign _20_ = _35_;
  assign _21_ = _36_;
  assign _38_ = _22_;
  assign _17_ = _15_;
  assign _16_ = _34_;
  assign _36_ = _17_;
  assign _14_ = _12_;
  assign _13_ = _33_;
  assign _35_ = _14_;
  assign \half_adder1.i_bit1  = i_bit1;
  assign \half_adder1.i_bit2  = i_bit2;
  assign half_carry1 = \half_adder1.o_carry ;
  assign half_sum1 = \half_adder1.o_sum ;
  assign _04_ = _11_;
  assign _03_ = _07_;
  assign _08_ = _04_;
  assign _02_ = _09_;
  assign _00_ = _05_;
  assign _01_ = _06_;
  assign _07_ = _02_;
endmodule
