/* Generated by Yosys 0.35+29 (git sha1 2a18fe5fa, clang++  -fPIC -Os) */

(* top =  1  *)
(* src = "./test.v:1.1-8.10" *)
module test(a, b, c);
  (* src = "./test.v:2.15-2.16" *)
  input a;
  wire a;
  (* src = "./test.v:3.15-3.16" *)
  input b;
  wire b;
  (* src = "./test.v:4.16-4.17" *)
  output c;
  wire c;
  assign c = a ^ (* src = "./test.v:7.20-7.25" *) b;
endmodule
