/* Generated by Yosys 0.35+29 (git sha1 2a18fe5fa, clang++  -fPIC -Os) */

(* top =  1  *)
(* src = "./test.v:1.1-8.10" *)
module test(i_a, i_b, o_c);
  (* src = "./mycells-not-working.v:13.7-13.8" *)
  wire _00_;
  (* src = "./mycells-not-working.v:13.10-13.11" *)
  wire _01_;
  (* src = "./mycells-not-working.v:14.8-14.9" *)
  wire _02_;
  (* src = "./mycells-not-working.v:8.7-8.8" *)
  wire _03_;
  (* src = "./mycells-not-working.v:8.10-8.11" *)
  wire _04_;
  (* src = "./mycells-not-working.v:9.8-9.9" *)
  wire _05_;
  (* src = "./mycells-not-working.v:3.7-3.8" *)
  wire _06_;
  (* src = "./mycells-not-working.v:4.8-4.9" *)
  wire _07_;
  (* src = "./mycells-not-working.v:13.7-13.8" *)
  wire _08_;
  (* src = "./mycells-not-working.v:13.10-13.11" *)
  wire _09_;
  (* src = "./mycells-not-working.v:14.8-14.9" *)
  wire _10_;
  (* src = "./test.v:2.15-2.18" *)
  wire _11_;
  (* src = "./test.v:3.15-3.18" *)
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  (* src = "./test.v:4.16-4.19" *)
  wire _16_;
  (* src = "./mycells-not-working.v:14.12-14.20" *)
  wire _17_;
  (* src = "./mycells-not-working.v:14.14-14.19" *)
  wire _18_;
  (* src = "./mycells-not-working.v:9.14-9.19" *)
  wire _19_;
  (* src = "./mycells-not-working.v:9.12-9.20" *)
  wire _20_;
  (* src = "./mycells-not-working.v:4.12-4.14" *)
  wire _21_;
  (* src = "./mycells-not-working.v:14.12-14.20" *)
  wire _22_;
  (* src = "./mycells-not-working.v:14.14-14.19" *)
  wire _23_;
  (* src = "./test.v:2.15-2.18" *)
  input i_a;
  wire i_a;
  (* src = "./test.v:3.15-3.18" *)
  input i_b;
  wire i_b;
  (* src = "./test.v:4.16-4.19" *)
  output o_c;
  wire o_c;
  assign _17_ = ~ (* src = "./mycells-not-working.v:14.12-14.20" *) _18_;
  assign _18_ = _00_ | (* src = "./mycells-not-working.v:14.14-14.19" *) _01_;
  assign _19_ = _03_ & (* src = "./mycells-not-working.v:9.14-9.19" *) _04_;
  assign _20_ = ~ (* src = "./mycells-not-working.v:9.12-9.20" *) _19_;
  assign _21_ = ~ (* src = "./mycells-not-working.v:4.12-4.14" *) _06_;
  assign _22_ = ~ (* src = "./mycells-not-working.v:14.12-14.20" *) _23_;
  assign _23_ = _08_ | (* src = "./mycells-not-working.v:14.14-14.19" *) _09_;
  assign _11_ = i_a;
  assign _12_ = i_b;
  assign o_c = _16_;
  assign _10_ = _22_;
  assign _08_ = _13_;
  assign _09_ = _15_;
  assign _16_ = _10_;
  assign _07_ = _21_;
  assign _06_ = _14_;
  assign _15_ = _07_;
  assign _05_ = _20_;
  assign _03_ = _11_;
  assign _04_ = _12_;
  assign _14_ = _05_;
  assign _02_ = _17_;
  assign _00_ = _11_;
  assign _01_ = _12_;
  assign _13_ = _02_;
endmodule
