[package]
name = "egg-rewrite-exp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.7", features = ["derive"] }
egglog = "0.1.0"
env_logger = "0.10.0"
log = "0.4.20"
regex = "1.10.2"
