/* Generated by Yosys 0.32 (git sha1 fbab08acf14, gcc 12.3.0 -fPIC -Os) */

(* top =  1  *)
(* src = "half-adder.v:2.1-18.10" *)
module half_adder(i_bit1, i_bit2, o_sum, o_carry);
  wire _0_;
  wire _1_;
  wire _2_;
  (* src = "half-adder.v:10.10-10.16" *)
  input i_bit1;
  wire i_bit1;
  (* src = "half-adder.v:11.10-11.16" *)
  input i_bit2;
  wire i_bit2;
  (* src = "half-adder.v:13.10-13.17" *)
  output o_carry;
  wire o_carry;
  (* src = "half-adder.v:12.10-12.15" *)
  output o_sum;
  wire o_sum;
  NOT _3_ (
    .A(i_bit2),
    .Y(_0_)
  );
  NOT _4_ (
    .A(i_bit1),
    .Y(_1_)
  );
  NOR _5_ (
    .A(_0_),
    .B(_1_),
    .Y(o_carry)
  );
  NOR _6_ (
    .A(i_bit2),
    .B(i_bit1),
    .Y(_2_)
  );
  NOR _7_ (
    .A(o_carry),
    .B(_2_),
    .Y(o_sum)
  );
endmodule
