/* Generated by Yosys 0.32 (git sha1 fbab08acf14, gcc 12.3.0 -fPIC -Os) */

(* top =  1  *)
(* src = "counter.v:1.1-12.10" *)
module counter(clk, rst, en, count);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  (* src = "counter.v:3.8-3.11" *)
  input clk;
  wire clk;
  (* src = "counter.v:4.19-4.24" *)
  output [1:0] count;
  wire [1:0] count;
  (* src = "counter.v:3.18-3.20" *)
  input en;
  wire en;
  (* src = "counter.v:3.13-3.16" *)
  input rst;
  wire rst;
  NAND _10_ (
    .A(en),
    .B(count[0]),
    .Y(_07_)
  );
  NOR _11_ (
    .A(en),
    .B(count[0]),
    .Y(_08_)
  );
  NOT _12_ (
    .A(_08_),
    .Y(_09_)
  );
  NAND _13_ (
    .A(_07_),
    .B(_09_),
    .Y(_02_)
  );
  NOR _14_ (
    .A(rst),
    .B(_02_),
    .Y(_00_)
  );
  NAND _15_ (
    .A(count[1]),
    .B(_07_),
    .Y(_03_)
  );
  NOT _16_ (
    .A(_03_),
    .Y(_04_)
  );
  NOR _17_ (
    .A(count[1]),
    .B(_07_),
    .Y(_05_)
  );
  NOR _18_ (
    .A(_04_),
    .B(_05_),
    .Y(_06_)
  );
  NOR _19_ (
    .A(rst),
    .B(_06_),
    .Y(_01_)
  );
  (* src = "counter.v:6.2-10.26" *)
  DFF _20_ (
    .C(clk),
    .D(_00_),
    .Q(count[0])
  );
  (* src = "counter.v:6.2-10.26" *)
  DFF _21_ (
    .C(clk),
    .D(_01_),
    .Q(count[1])
  );
endmodule
