/* Generated by Yosys 0.32+74 (git sha1 316e2bdcb, gcc 12.3.0 -fPIC -Os) */

(* top =  1  *)
(* src = "full_adder.v:1.1-34.10" *)
module full_adder(i_bit1, i_bit2, i_cin, o_sum, o_carry);
  wire _0_;
  wire _1_;
  (* hdlname = "half_adder1 i_bit1" *)
  (* src = "full_adder.v:20.15-25.7|half_adder.v:11.10-11.16" *)
  wire \half_adder1.i_bit1 ;
  (* hdlname = "half_adder1 i_bit2" *)
  (* src = "full_adder.v:20.15-25.7|half_adder.v:12.10-12.16" *)
  wire \half_adder1.i_bit2 ;
  (* hdlname = "half_adder2 o_carry" *)
  (* src = "full_adder.v:26.15-31.7|half_adder.v:14.10-14.17" *)
  wire \half_adder2.o_carry ;
  (* hdlname = "half_adder2 o_sum" *)
  (* src = "full_adder.v:26.15-31.7|half_adder.v:13.10-13.15" *)
  wire \half_adder2.o_sum ;
  (* src = "full_adder.v:10.11-10.17" *)
  input i_bit1;
  wire i_bit1;
  (* src = "full_adder.v:11.11-11.17" *)
  input i_bit2;
  wire i_bit2;
  (* src = "full_adder.v:12.11-12.16" *)
  input i_cin;
  wire i_cin;
  (* src = "full_adder.v:14.11-14.18" *)
  output o_carry;
  wire o_carry;
  (* src = "full_adder.v:13.11-13.16" *)
  output o_sum;
  wire o_sum;
  assign _0_ = i_bit2 ^ i_bit1;
  assign _1_ = ~(i_bit2 & i_bit1);
  assign o_carry = _0_ & ~(_1_);
  assign o_sum = i_bit2 | i_bit1;
  assign \half_adder2.o_carry  = o_carry;
  assign \half_adder2.o_sum  = o_sum;
  assign \half_adder1.i_bit2  = i_bit2;
  assign \half_adder1.i_bit1  = i_bit1;
endmodule
