/* Generated by Yosys 0.32+74 (git sha1 316e2bdcb, gcc 12.3.0 -fPIC -Os) */

(* top =  1  *)
(* src = "full_adder.v:1.1-40.10" *)
module full_adder(i_bit1, i_bit2, i_cin, o_sum, o_carry);
  (* src = "full_adder.v:22.15-27.7|half_adder.v:17.20-17.35" *)
  wire _0_;
  (* src = "full_adder.v:22.15-27.7|half_adder.v:16.20-16.35" *)
  wire _1_;
  (* src = "full_adder.v:28.15-33.7|half_adder.v:17.20-17.35" *)
  wire _2_;
  (* src = "full_adder.v:28.15-33.7|half_adder.v:16.20-16.35" *)
  wire _3_;
  (* src = "full_adder.v:34.21-34.46" *)
  wire _4_;
  (* hdlname = "half_adder1 i_bit1" *)
  (* src = "full_adder.v:22.15-27.7|half_adder.v:11.10-11.16" *)
  wire \half_adder1.i_bit1 ;
  (* hdlname = "half_adder1 i_bit2" *)
  (* src = "full_adder.v:22.15-27.7|half_adder.v:12.10-12.16" *)
  wire \half_adder1.i_bit2 ;
  (* hdlname = "half_adder1 o_carry" *)
  (* src = "full_adder.v:22.15-27.7|half_adder.v:14.10-14.17" *)
  wire \half_adder1.o_carry ;
  (* hdlname = "half_adder1 o_sum" *)
  (* src = "full_adder.v:22.15-27.7|half_adder.v:13.10-13.15" *)
  wire \half_adder1.o_sum ;
  (* hdlname = "half_adder2 i_bit1" *)
  (* src = "full_adder.v:28.15-33.7|half_adder.v:11.10-11.16" *)
  wire \half_adder2.i_bit1 ;
  (* hdlname = "half_adder2 i_bit2" *)
  (* src = "full_adder.v:28.15-33.7|half_adder.v:12.10-12.16" *)
  wire \half_adder2.i_bit2 ;
  (* hdlname = "half_adder2 o_carry" *)
  (* src = "full_adder.v:28.15-33.7|half_adder.v:14.10-14.17" *)
  wire \half_adder2.o_carry ;
  (* hdlname = "half_adder2 o_sum" *)
  (* src = "full_adder.v:28.15-33.7|half_adder.v:13.10-13.15" *)
  wire \half_adder2.o_sum ;
  (* src = "full_adder.v:17.11-17.22" *)
  wire half_carry1;
  (* src = "full_adder.v:18.11-18.22" *)
  wire half_carry2;
  (* src = "full_adder.v:16.11-16.20" *)
  wire half_sum1;
  (* src = "full_adder.v:10.11-10.17" *)
  input i_bit1;
  wire i_bit1;
  (* src = "full_adder.v:11.11-11.17" *)
  input i_bit2;
  wire i_bit2;
  (* src = "full_adder.v:12.11-12.16" *)
  input i_cin;
  wire i_cin;
  (* src = "full_adder.v:14.11-14.18" *)
  output o_carry;
  wire o_carry;
  (* src = "full_adder.v:13.11-13.16" *)
  output o_sum;
  wire o_sum;
  assign _0_ = \half_adder1.i_bit1  & (* src = "full_adder.v:22.15-27.7|half_adder.v:17.20-17.35" *) \half_adder1.i_bit2 ;
  assign _1_ = \half_adder1.i_bit1  ^ (* src = "full_adder.v:22.15-27.7|half_adder.v:16.20-16.35" *) \half_adder1.i_bit2 ;
  assign _2_ = \half_adder2.i_bit1  & (* src = "full_adder.v:28.15-33.7|half_adder.v:17.20-17.35" *) \half_adder2.i_bit2 ;
  assign _3_ = \half_adder2.i_bit1  ^ (* src = "full_adder.v:28.15-33.7|half_adder.v:16.20-16.35" *) \half_adder2.i_bit2 ;
  assign _4_ = half_carry1 | (* src = "full_adder.v:34.21-34.46" *) half_carry2;
  assign o_carry = _4_;
  assign \half_adder1.o_sum  = _1_;
  assign \half_adder1.o_carry  = _0_;
  assign half_carry1 = \half_adder1.o_carry ;
  assign half_sum1 = \half_adder1.o_sum ;
  assign \half_adder1.i_bit2  = i_bit2;
  assign \half_adder1.i_bit1  = i_bit1;
  assign \half_adder2.o_sum  = _3_;
  assign \half_adder2.o_carry  = _2_;
  assign half_carry2 = \half_adder2.o_carry ;
  assign o_sum = \half_adder2.o_sum ;
  assign \half_adder2.i_bit2  = half_sum1;
  assign \half_adder2.i_bit1  = i_cin;
endmodule
